### ISSUE TITLE
require-jsdoc doesn't apply to ampersand-style methods

### ISSUE THREAD

**Issue by ianwremmel** [ciscospark/web-styleguide#4]
Fixable with the following config

```yml
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: false
        FunctionExpression: true
```
